title: Agentic Dev Guide
description: Guidance for the new era of Agentic AI Engineering. Patterns, strategies, and best practices.
remote_theme: just-the-docs/just-the-docs
url: "https://gabrigabs.github.io"
baseurl: "/agentic-dev-guide"

color_scheme: atlas
logo: "/assets/images/mark.svg"
favicon_ico: "/assets/images/favicon.svg"

search_enabled: true
search_heading_level: 2
heading_anchors: true
nav_sort: case_insensitive
back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "English":
    - "/agentic-dev-guide/en/"
  "PortuguÃªs":
    - "/agentic-dev-guide/pt/"
  "GitHub Repository":
    - "//github.com/gabrigabs/agentic-dev-guide"

footer_content: "Copyright &copy; 2026 Agentic Dev Guide Contributors"
